DROP DATABASE IF EXISTS MQF2020;
CREATE DATABASE MQF2020;
USE MQF2020;

CREATE TABLE studentGrade 
(
studentID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
firstname VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
GPA DECIMAL(2,1) NOT NULL 
);
